# SPDX-License-Identifier: MPL-2.0
include_guard(GLOBAL)

option(MOHIDNG_BUILD_BENCHMARKS "Build scientific verification benchmarks" OFF)
option(MOHIDNG_BUILD_CASES "Build scientific application cases" OFF)
option(MOHIDNG_REGISTER_SCIENTIFIC_TESTS "Also register enabled benchmarks/cases with CTest" OFF)

option(MOHIDNG_ENABLE_WARNINGS "Enable warnings on MohidNG targets" ON)
option(MOHIDNG_ENABLE_LTO "Enable supported IPO/LTO in optimized configurations" ON)
option(MOHIDNG_ENABLE_NATIVE_ARCH "Optimize Release/RelWithDebInfo for this CPU" OFF)
option(MOHIDNG_ENABLE_SANITIZERS "Enable ASan/UBSan in a separate diagnostic build" OFF)
option(MOHIDNG_ENABLE_COVERAGE "Instrument a separate build for coverage" OFF)

if(MOHIDNG_ENABLE_SANITIZERS AND MOHIDNG_ENABLE_COVERAGE)
  message(FATAL_ERROR "Use separate build directories for sanitizers and coverage.")
endif()

set(MOHIDNG_INSTRUMENTED_BUILD OFF)
if(MOHIDNG_ENABLE_SANITIZERS OR MOHIDNG_ENABLE_COVERAGE)
  set(MOHIDNG_INSTRUMENTED_BUILD ON)
endif()

set(MOHIDNG_MSVC_FRONTEND OFF)
if(MSVC OR CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
  set(MOHIDNG_MSVC_FRONTEND ON)
endif()

set(MOHIDNG_GNU_STYLE_FRONTEND OFF)
if(CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$" AND NOT MOHIDNG_MSVC_FRONTEND)
  set(MOHIDNG_GNU_STYLE_FRONTEND ON)
endif()

include(CheckCXXCompilerFlag)

if(MOHIDNG_ENABLE_NATIVE_ARCH)
  if(CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "MOHIDNG_ENABLE_NATIVE_ARCH cannot be used while cross-compiling.")
  endif()
  if(NOT MOHIDNG_GNU_STYLE_FRONTEND)
    message(FATAL_ERROR "Native CPU optimization currently requires the GCC/Clang command-line interface.")
  endif()
  check_cxx_compiler_flag("-march=native" MOHIDNG_HAS_MARCH_NATIVE)
  if(NOT MOHIDNG_HAS_MARCH_NATIVE)
    message(FATAL_ERROR "This compiler/architecture does not support -march=native.")
  endif()
endif()

function(mohidng_check_instrumentation flag result)
  set(CMAKE_REQUIRED_LINK_OPTIONS "${flag}")
  check_cxx_compiler_flag("${flag}" "${result}")
  if(NOT ${result})
    message(FATAL_ERROR "Requested instrumentation is not supported: ${flag}")
  endif()
endfunction()

if(MOHIDNG_INSTRUMENTED_BUILD)
  if(NOT MOHIDNG_GNU_STYLE_FRONTEND)
    message(FATAL_ERROR "MohidNG instrumentation currently requires GCC or Clang with a GNU-style interface.")
  endif()
  if(MOHIDNG_ENABLE_SANITIZERS)
    mohidng_check_instrumentation("-fsanitize=address,undefined" MOHIDNG_HAS_SANITIZERS)
  else()
    mohidng_check_instrumentation("--coverage" MOHIDNG_HAS_COVERAGE)
  endif()
endif()

set(MOHIDNG_IPO_ACTIVE OFF)
if(MOHIDNG_ENABLE_LTO AND NOT MOHIDNG_INSTRUMENTED_BUILD)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT MOHIDNG_IPO_ACTIVE OUTPUT mohidng_ipo_error LANGUAGES CXX)
  if(NOT MOHIDNG_IPO_ACTIVE)
    message(WARNING "MohidNG IPO/LTO is unavailable: ${mohidng_ipo_error}")
  endif()
endif()

message(STATUS "MohidNG optimized configurations: Release, RelWithDebInfo")
message(STATUS "MohidNG IPO/LTO active in optimized configurations: ${MOHIDNG_IPO_ACTIVE}")
message(STATUS "MohidNG native CPU requested: ${MOHIDNG_ENABLE_NATIVE_ARCH}")
message(STATUS "MohidNG sanitizers: ${MOHIDNG_ENABLE_SANITIZERS}; coverage: ${MOHIDNG_ENABLE_COVERAGE}")
if(MOHIDNG_INSTRUMENTED_BUILD)
  message(STATUS "MohidNG diagnostic build: IPO and native CPU optimization are disabled")
endif()
if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
  message(STATUS "No build type selected; choose Release for optimized execution")
endif()
