# SPDX-License-Identifier: MPL-2.0
include_guard(GLOBAL)

function(mohidng_add_scientific_programs)
  if(NOT MOHIDNG_BUILD_BENCHMARKS AND NOT MOHIDNG_BUILD_CASES)
    return()
  endif()
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/MohidNGPrograms.cmake")

  foreach(group IN ITEMS benchmarks cases)
    string(TOUPPER "${group}" key)
    if(NOT MOHIDNG_BUILD_${key})
      continue()
    endif()
    if(group STREQUAL "benchmarks")
      set(prefix "bench_")
    else()
      set(prefix "case_")
    endif()
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS
      "${PROJECT_SOURCE_DIR}/${group}/${prefix}*.cc"
      "${PROJECT_SOURCE_DIR}/${group}/${prefix}*.cpp")
    list(SORT sources)
    add_custom_target("${group}")
    add_custom_target("run_all_${group}")
    if(NOT sources)
      message(STATUS "[MohidNG ${group}] No ${prefix}*.cc or ${prefix}*.cpp programs yet")
    endif()
    foreach(source IN LISTS sources)
      if(MOHIDNG_REGISTER_SCIENTIFIC_TESTS)
        mohidng_add_program("${source}" "${group}")
      else()
        mohidng_add_program("${source}" "${group}" NO_CTEST)
      endif()
    endforeach()
  endforeach()
endfunction()
